name: Build, test, and deploy on PROD

# Controls when the action will run.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Prepare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      NEXT_TELEMETRY_DISABLED: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master ðŸ›Žï¸

      - name: Cache  ðŸ’¾
        uses: actions/cache@v2.1.6
        id: cache-deps
        with:
          path: |
            **/.yarn
            **/node_modules/
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies ðŸ”§
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: yarn --frozen-lockfile
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Audit ðŸ›¡ï¸
        run: yarn audit
        continue-on-error: true

      - name: Lint ðŸ§¹
        run: yarn lint

      - name: Units tests ðŸ›
        run: yarn test:coverage

      - name: Build ðŸ“¦
        run: yarn build
        env:
          CI: true

      - name: Merge dev -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
